### ISSUE TITLE
[OLD] Legacy Italian Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/it.react.dev#1]
## Maintainer List

* @deblasis
* @LucaBlackDragon
* @lssmn 

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

# Beta website (https://beta.reactjs.org/)

We are now focusing our translation efforts on the new Beta website.

The new docs aren't fully written yet, and some parts will definitely change. However, a lot of the pages are already "stable". We suggest to use this checklist for the beginning. ✅ means "ok to translate", 🔴 means "don't translate yet".

- [x] ✅ Installation (note: a lot of content here is similar to old website) (@deblasis) #374
  - [x] ✅ Start a New React Project (@deblasis) #374
  - [ ] ✅ Add React to a Website
  - [x] ✅ Editor Setup (@deblasis) #374
  - [ ] ✅ React Developer Tools
- [ ] 🔴 Quick Start (don't translate the index page yet, it will change)
  - [ ] ✅ Thinking in React
- [ ] 🔴 Describing the UI (don't translate the index page yet, it might change)
  - [ ] ✅ Your First Component
  - [ ] ✅ Importing and Exporting Components
  - [ ] ✅ Writing Markup with JSX
  - [ ] ✅ JavaScript in JSX with Curly Braces
  - [ ] ✅ Passing Props to a Component
  - [ ] ✅ Conditional Rendering
  - [ ] ✅ Rendering Lists
  - [ ] ✅ Keeping Components Pure
- [ ] 🔴 Adding Interactivity (don't translate the index page yet, it might change)
  - [ ] ✅ Responding to Events
  - [ ] ✅ State: A Component's Memory
  - [ ] ✅ Render and Commit
  - [ ] ✅ State as a Snapshot
  - [ ] ✅ Queueing a Series of State Updates
  - [ ] ✅ Updating Objects in State
  - [ ] ✅ Updating Arrays in State
- [ ] 🔴 Managing State (don't translate the index page yet, it might change)
  - [ ] ✅ Reacting to Input with State
  - [ ] ✅ Choosing the State Structure
  - [ ] ✅ Sharing State Between Components
  - [ ] ✅ Preserving and Resetting State
  - [ ] ✅ Extracting State Logic into a Reducer
  - [ ] ✅ Passing Data Deeply with Context
  - [ ] ✅ Scaling Up with Reducer and Context
- [ ] 🔴 Escape Hatches (not written yet)
  - [ ] ✅ Referencing Values with Refs
  - [ ] ✅ Manipulating the DOM with Refs

# Legacy website

Emojis:
| Emoji | Description|
| -| - |
|✅|Translated in legacy website |
|⏹| Stale (no need to translate anymore) |

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] ✅Home Page (@deblasis) #5
* [x] ✅Tutorial (@deblasis) #6

### Basics

* [x] ✅Hello World (@LucaBlackDragon) #4
* [x] ✅Introducing JSX (@LucaBlackDragon) #14 
* [x] ✅Rendering Elements (@deblasis) #16 
* [x] ✅Components and Props (@deblasis) #101 
* [x] ✅State and Lifecycle (@LucaBlackDragon) #18 
* [x] ✅Handling Events (@lssmn) #20 
* [x] ✅Conditional Rendering (@deblasis) #21 
* [x] ✅Lists and Keys (@lssmn) #22
* [x] ✅Forms (@deblasis) #23
* [x] ✅Lifting State Up (@lssmn) #24
* [x] ✅Composition vs Inheritance (@deblasis) #25 
* [x] ✅Thinking in React (@deblasis) #26 

### API Reference

* [x] ✅React (@LucaBlackDragon) #130
* [x] ✅React.Component (@LucaBlackDragon) #27
* [x] ✅ReactDOM (@Manugal) #28
* [x] ✅ReactDOMServer (@Manugal) #29
* [x] ✅DOM Elements (@deblasis) #30
* [x] ✅SyntheticEvent (@frankcalise) #31
* [x] ✅Test Utilities (@guerrap) #32
* [x] ✅Shallow Renderer (@deblasis) #33
* [x] ✅Test Renderer (@Manugal) #34
* [x] ✅JS Environment Requirements (@deblasis) #35
* [x] ✅Glossary (@Manugal) #36 

### Navigation

These are the navigation links that appear in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] ✅tutorial/nav.yml (@deblasis) #37 
* [x] ✅docs/nav.yml (@deblasis) #38 

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] ✅Getting Started (@deblasis) #39 
* [x] ✅Add React to a Website (@LucaBlackDragon ) #40 
* [x] ✅Create a New React App (@LucaBlackDragon ) #41
* [x] ✅CDN Links (@Manugal) #42

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [x] ✅Introducing Hooks (@deblasis) #43
  * [x] ✅Hooks at a Glance (@deblasis) #44
  * [x] ✅Using the State Hook (@one89) #45
  * [x] ⏹Using the Effect Hook (@one89) #46
  * [x] ✅Rules of Hooks (@hawz) #47
  * [x] ✅Building Your Own Hooks (@hawz) #48
  * [x] ⏹Hooks API Reference (@acifani) #49
  * [x] ⏹Hooks FAQ (@acifani) #50

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [x] ⏹dont-call-proptypes #51 
* [x] ✅invalid-aria-prop  (@mbellagamba) #52
* [x] ⏹invalid-hook-call-warning #53
* [x] ⏹legacy-factories #54
* [x] ⏹refs-must-have-owner #55
* [x] ⏹special-props #56
* [x] ⏹unknown-prop #57

### Advanced Guides

* [x] ✅Accessibility (@DennisBoanini) #58
* [x] ✅Code-Splitting (@DennisBoanini) #59
* [x] ⏹Context (@vikysingh) #60
* [x] ✅Error Boundaries (@DennisBoanini) #61
* [x] ✅Forwarding Refs (@DennisBoanini) #62
* [x] ✅Fragments (@carmensantoro) #63
* [x] ⏹Higher-Order Components (@DennisBoanini) #64
* [x] ⏹Integrating with Other Libraries #66
* [x] ✅JSX In Depth (@DennisBoanini) #65
* [x] ⏹Optimizing Performance #67
* [x] ⏹Portals #68
* [x] ⏹React Without ES6 #69
* [x] ✅React Without JSX (@mattia-sanfilippo) #70
* [x] ✅Reconciliation (@mattveraldi)  #71
* [x] ⏹Refs and the DOM #72
* [x] ⏹Render Props #73
* [x] ⏹Static Type Checking #74
* [x] ⏹Strict Mode #75
* [x] ⏹Typechecking With PropTypes #76
* [x] ⏹Uncontrolled Components #77
* [x] ⏹Web Components #78

### FAQ

* [x] ✅APIs and AJAX (@adifsgaid) #79 
* [x] ⏹Babel, JSX, and Build Steps #80
* [x] ⏹Passing Functions to Components #81
* [x] ⏹Component State #82
* [x] ✅Styling and CSS (@alessioitalo) #83
* [x] ✅File Structure (@mattia-sanfilippo) #84
* [x] ⏹Versioning Policy #85
* [x] ⏹Virtual DOM and Internals #86

### Contributing

Priority: Low

* [x] ⏹How to Contribute #87
* [x] ⏹Codebase Overview #88
* [x] ⏹Implementation Notes #89
* [x] ⏹Design Principles #90

### Components

Components in `src/components` that have some text in them.

* [x] ⏹CodeEditor #91
* [x] ⏹CodeExample #92
* [x] ⏹ErrorDecoder #93
* [x] ⏹LayoutFooter #94
* [x] ⏹LayoutHeader #95
* [x] ⏹MarkdownPage #96

## Additional Translations

These are not the primary translation targets.

* [x] ⏹Blog #97
* [x] ⏹Community #98

**Comment by deblasis** [comment]
Fantastic! Thanks @tesseralis !

Actually, I already have **Homepage** ready for review and around 40% of the tutorial. 
These have been done forking the base project in an effort to teach React to some folks during a meetup, showing them how to setup the environment and by let them follow the tutorial of course... while translating it 😄 

I'll update the issue later.

@LucaBlackDragon, please pick something else so that we don't do things twice! 👍 Obviously, I'll ask you to review.

Ciaoo!

**Comment by tesseralis** [comment]
Great! @deblasis once you accept the invitation to join the reactjs organization, you should be able to edit the issue itself. Do something like:

[ ] Home Page (@deblasis) #2

This way people can keep track!

**Comment by LucaBlackDragon** [comment]
@tesseralis thank you!
@deblasis I updated this issue assigning **Homepage** and **Tutorial** to you and picked **Hello World** for starters. Buona serata e buon lavoro!

**Comment by LucaBlackDragon** [comment]
I have also opened and pinned two issues for the Style Guide and Glossary, should we need it

**Comment by deblasis** [comment]
Great! I can see some **very** good progress here already.

I have updated the issue adding work items tracking emojis (not super useful now that it's just the two of us but I reckon it will help loads when we will have many contributors 😄 hopefully!)

**Comment by deblasis** [comment]
I have created a new PR (#8), also removed the tracking emojis just because... better to use tags. I will copy a few of the tags used by our Brazilian friends and let's see how that goes! 😉

**Comment by medenagan** [comment]
Hey! Can I join? I'd like to help translate a page too.

**Comment by deblasis** [comment]
Hi @medenagan ! Of course! Feel free to pick a page from the list and follow the instructions, shout if you need help with anything.

**Comment by deblasis** [comment]
Added CircleCI webhook

**Comment by medenagan** [comment]
@deblasis @LucaBlackDragon cool! Is it okay if I pick `API Reference > React`? I don't have any  preference :smile:

**Comment by LucaBlackDragon** [comment]
Ok I'll assign that page to you! Just be sure to read the style guide and glossary before beginning to translate (and feel free to contribute to those too)

**Comment by deblasis** [comment]
Hi guys! I think we need to attract more people, we need help! I was thinking about creating issues with the flags "help wanted" and "good first issue" for all the open/unassigned tasks in the progress issue.

I know that there are a lot of people that search for those tags in order to find projects to contribute on. 

Then I thought... I can automate this thing and maybe other teams could find this script useful! So... I am gonna run it then I'm gonna shout about it and let's see what happens :D perhaps you guys could do the same!

**Comment by lssmn** [comment]
Ciao guys! I have been looking for this for days and then I got distracted by work 😅I would love to contribute!

I can work on **Basics -> Handling Events** if nobody has taken it already (I actually have an almost ready **Hooks -> Introducing Hooks** as I was excited to do it but then realised that it is too early).

Let me know please! @deblasis @LucaBlackDragon

**Comment by deblasis** [comment]
Ciao @lssmn! Fantastic! Please go on, read the instructions, assign the issue to yourself and start working on it at your own pace. I suggest we follow the advice we received in terms of focusing on core pages first. The newest ones are more likely to change I guess, also, the website is not live yet, otherwise yeah perhaps having a hot topic translated would have been better IMHO.

Welcome aboard 😄

**Comment by LucaBlackDragon** [comment]
Welcome!

**Comment by deblasis** [comment]
Added Netlify hook on master and status badges in `README.md` so that we can preview the end result/see the status at a glance

**Comment by lssmn** [comment]
I'm going to work on **Basics -> Lists and Keys** #22 👌

**Comment by deblasis** [comment]
Fantastic(o)! Would you mind assigning the issue to yourself? 😉

**Comment by lssmn** [comment]
I don't have the permissions to assign issues or add labels unfortunately 🤓

**Comment by LucaBlackDragon** [comment]
@lssmn I added you to the Maintainers list in this issue

**Comment by GCrispino** [comment]
Ciao! Can I take **Composition vs Inheritance** (#25)?

**Comment by deblasis** [comment]
Ciao! Sure @GCrispino ! All yours 😄

**Comment by tesseralis** [comment]
So... I recommend not having an issue for each page to translate. It just gets too cluttered and doesn't really add anything meaningful.

**Comment by LucaBlackDragon** [comment]
> 
> 
> So... I recommend not having an issue for each page to translate. It just gets too cluttered and doesn't really add anything meaningful.

OK @tesseralis so you would rather we close all the issues and stick with the checkbox list in this issue alone, am I right? @deblasis is it OK for you?

**Comment by LucaBlackDragon** [comment]
> 
> 
> @deblasis @LucaBlackDragon cool! Is it okay if I pick `API Reference > React`? I don't have any preference 😄

Hi @medenagan, any news about this page translation? Do you need help?

**Comment by deblasis** [comment]
> > So... I recommend not having an issue for each page to translate. It just gets too cluttered and doesn't really add anything meaningful.
> 
> OK @tesseralis so you would rather we close all the issues and stick with the checkbox list in this issue alone, am I right? @deblasis is it OK for you?

Honestly, strictly IMHO, I believe we are doing just fine, there's no clutter as the issues follow a convention (that we enforced programmatically). 

Also I believe that one of my "cry for help tweets" 🤣 :
- https://twitter.com/deBlasisAlex/status/1097061582301990912
- https://twitter.com/deBlasisAlex/status/1097061517718106112

even if I have basically **0** followers, allowed us to have a new member in the team, right @lssmn ? 😄 

Without issues, there is nothing that keeps track of the work being done from the start... Unless a WIP PR is created contextually with the beginning of the translation of a page... Which, sounds like a messy approach to me, again, IMHO.

Currently, the only open "item" which we don't know anything about is `API Reference -> React`. This is because when I launched the script that created the issues, I wanted to skip the items already "assigned" (as in... having a GitHub handle next to them) and that one is the only one left open. If it had an open issue it would have helped with keeping track of when it was opened and to follow-up in a contextual way, instead of cluttering this issue with comments of various nature. 

Last but not least: I am happy either way, all I am trying to do here is to be helpful in a way or the other, I can't help being passionate... you know... 🇮🇹  😄

**Comment by tesseralis** [comment]
@deblasis alright! In the end it's up to you on what method works best. This is just something I've noticed from seeing other translations. e.g. Spanish started off with issues per page but ended up closing all of them. The only request is that you keep this issue updated so I can keep isreacttranslatedyet.com accurate :)

**Comment by deblasis** [comment]
Of course! Issue #1 will always be kept updated no matter what so that
isreacttranslatedyet.com is accurate! 😊

**Comment by frankcalise** [comment]
Ciao! Could I start with the docs/nav.yml #38? I realize it's small / slightly out of top priority but would like to contribute and get my feet wet before taking on some of the bigger pages 👍

**Comment by deblasis** [comment]
Hi Frank! Nice seeing you coming from my "tweeting for help"! 😊

Hehe! Please read above...

It says:
> Navigation
> These are the navigation links that appear in the sidebar. Possibly wait
until
> the corresponding sections are translated to do these.
>
>   tutorial/nav.yml #37
>   docs/nav.yml #38

#38 is likely to be completed by itself after all the linked pages are
translated as we tend to translate the titles of the various pages inside
`docs/nav.yml` as well for consistency

Please try again choosing another page :)

**Comment by frankcalise** [comment]
Ok no problem, how about SyntheticEvent (#31)?

**Comment by deblasis** [comment]
All yours @frankcalise ! :)

**Comment by guerrap** [comment]
Ciao, can I start working on #32?

**Comment by deblasis** [comment]
Ciao @guerrap , sure! Please read the instructions and do not hesitate to ask if you have any question.

**Comment by LucaBlackDragon** [comment]
> 
> 
> > @deblasis @LucaBlackDragon cool! Is it okay if I pick `API Reference > React`? I don't have any preference 😄
> 
> Hi @medenagan, any news about this page translation? Do you need help?

Hi @medenagan, if you are still with us please let us know!
Meanwhile, I'll start to work on `API Reference > React` too.

**Comment by one89** [comment]
Ciao! Can I take **Hooks -> Using the Effect Hook** #46 ?

**Comment by LucaBlackDragon** [comment]
> 
> 
> Ciao! Can I take **Hooks -> Using the Effect Hook** #46 ?

Of course @one89 ! Sorry to reply so late!

**Comment by hawz** [comment]
Ciao! Can I start working on **Hooks -> Rules of Hooks** #47 ?

**Comment by LucaBlackDragon** [comment]
Of course! Just be sure to read the guidelines first
________________________________

**Comment by hawz** [comment]
Hi, can I take *Hooks -> Building Your Own Hooks* #48? Also, #47 should be already done and merged into master, so the issue is outdated. Thank you!

**Comment by deblasis** [comment]
Ciao @hawz ! Sure, all yours.
I have updated the issues accordingly. 
👍

**Comment by acifani** [comment]
Hey everyone, I can take #49 and #50 if they're still available

**Comment by LucaBlackDragon** [comment]
Hi @acifani, sure!
I've update the issue

**Comment by carmensantoro** [comment]
Hi! Can I take Fragments #63? I have already translated it

**Comment by DennisBoanini** [comment]
Ciao! Can I start working on #65 ?

**Comment by DennisBoanini** [comment]
Ciao! Can I start working on #58 ?  @deblasis @LucaBlackDragon @lssmn

**Comment by DennisBoanini** [comment]
Ciao! Can I start working on #59 ? @deblasis

**Comment by vikysingh** [comment]
Ciao! Can I work on #60 ? @deblasis @LucaBlackDragon @lssmn

**Comment by DennisBoanini** [comment]
Ciao! Can I start working on #61 ? @deblasis @LucaBlackDragon @lssmn

**Comment by mattveraldi** [comment]
Ciao, can I take Reconciliation #71 ?

**Comment by DennisBoanini** [comment]
Ciao I'd like to start work on https://github.com/reactjs/it.reactjs.org/issues/62 @deblasis

**Comment by deblasis** [comment]
Ciao @DennisBoanini ! All yours 👍

**Comment by adifsgaid** [comment]
Hello 😊, I would love to start working on FAQ page number #79.

**Comment by mattia-sanfilippo** [comment]
Ciao! Can I start working on #84 ?

**Comment by DennisBoanini** [comment]
Ciao I'd like to start work on #64  @deblasis

**Comment by deblasis** [comment]
> Ciao! Can I start working on #70 ?

All yours @mattia-sanfilippo !

**Comment by deblasis** [comment]
Ciao! 

We are now translating the new website that's currently in beta! (https://beta.reactjs.org/) 

All the ongoing translations are suspended as it only makes sense to focus on the new website content as described [here](https://github.com/reactjs/reactjs.org/issues/4135).

This issue has been updated. More info in #328

**Comment by deblasis** [comment]
Ciao @LucaBlackDragon e @lssmn ! Long time no see!! Come va?

Siete ancora interessati a collaborare? Ho appena creato la PR #374 e mi farebbe piacere che qualcuno gli dia uno sguardo :) 

Nessun problema se non avete tempo.

**Comment by gaearon** [comment]
Thanks to everyone who contributed to the old website translation!
Started a new issue for the new website: https://github.com/reactjs/it.react.dev/issues/418
