### ISSUE TITLE
Beta Website translation kick-off

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.react.dev#328]
This issue tracks the tasks necessary to have the beta website translations aligned with upstream.

- [x] Close all the Current Issues related to the `old/current` website
- [x] Update Readme.MD #329 
- [x] Update Issue #1

Then we'll need to translate some content 
- [ ] Installation (note: a lot of content here is similar to old website) (@deblasis) #374
  - [ ] Start a New React Project (@deblasis) #374
  - [ ] Add React to a Website
  - [ ] Editor Setup (@deblasis) #374
  - [ ] React Developer Tools (@mattia-sanfilippo)

After that we need to:
- [ ] Ask on the [Beta translation issue 4135 upstream](https://github.com/reactjs/reactjs.org/issues/4135) to setup the project

That should be it for the setup. 

Any additions/comments are more than welcome

**Comment by theringsofsaturn** [comment]
Hello, I would like to translate the new Beta site. I can pick "Start a New React Project" if no one else is already doing it.

**Comment by mattia-sanfilippo** [comment]
Hey @deblasis 👋🏻 
Can I translate "React Developer Tools"?
Thanks 😄

**Comment by deblasis** [comment]
> Hey @deblasis 👋🏻 Can I translate "React Developer Tools"? Thanks 😄

Hey @mattia-sanfilippo ! Of course! All yours 😃

**Comment by gaearon** [comment]
Hi folks,

Just a heads-up that we've done our best to bring `main` and `legacy` branches up-to-date with upstream. This brings you to the latest visual design and sets up all the redirects. We don't anticipate more changes necessary on `legacy`. For `main`, there's a few things you need to be aware of:

- Keep in mind translating UI is best done closer to the end. We plan to make non-trivial code changes to the repo over the next few months. So it's best to focus on the content rather than on UI components.
- The homepage is untranslated so ideally it would be good if you could do a pass at that. For now, unfortunately it requires messing with the code file.

Thank you so much for your cooperation!

**Comment by deblasis** [comment]
Hi @gaearon thanks for the heads up and the big hand.

We'll focus on the home page as a priority and follow the guidelines you just highlighted moving forward.

Thanks!

**Comment by gaearon** [comment]
Let's track this in https://github.com/reactjs/it.react.dev/issues/418.
